### ISSUE TITLE
RuntimeError: Failed fetching audio key! gid: 046ef5eaff02458f9a4fdb6d0465d163, fileId: 5c36cdc253cfafce561e7d8a3dd21e72aa7fe6f3

### ISSUE THREAD

**Issue by Footsiefat** [kokarare1212/librespot-python#49]
![image](https://user-images.githubusercontent.com/12180913/124718547-502b5580-df5a-11eb-8d55-93c12970abf4.png)

**Comment by kokarare1212** [comment]
Thank you for your inquiry.
Is the account you are logged into a free account?
In this case, due to restrictions on Spotify's side, you will not be able to stream at the highest quality.
I have made some changes, so please try downloading and running it again.
Then try "quality 160" the first time you run it.

**Comment by Footsiefat** [comment]
YOU BRILLIANT PERSON!! IT BLIDDY WORKED!!!
